spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/cp?currentSchema=public
    #url: jdbc:postgresql://localhost:5432/cp?currentSchema=public
    username: test
    password: test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true